//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.26 at 10:45:29 AM CDT 
//


package com.tyson.hpqcjapi.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the alm.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Testsuite_QNAME = new QName("", "testsuite");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: alm.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Testsuites }
     * 
     */
    public Testsuites createTestsuites() {
        return new Testsuites();
    }

    /**
     * Create an instance of {@link com.tyson.hpqcjapi.types.Testsuite }
     * 
     */
    public com.tyson.hpqcjapi.types.Testsuite createTestsuite() {
        return new com.tyson.hpqcjapi.types.Testsuite();
    }

    /**
     * Create an instance of {@link com.tyson.hpqcjapi.types.Testsuite.Testcase }
     * 
     */
    public com.tyson.hpqcjapi.types.Testsuite.Testcase createTestsuiteTestcase() {
        return new com.tyson.hpqcjapi.types.Testsuite.Testcase();
    }

    /**
     * Create an instance of {@link com.tyson.hpqcjapi.types.Testsuite.Properties }
     * 
     */
    public com.tyson.hpqcjapi.types.Testsuite.Properties createTestsuiteProperties() {
        return new com.tyson.hpqcjapi.types.Testsuite.Properties();
    }

    /**
     * Create an instance of {@link Testsuites.Testsuite }
     * 
     */
    public Testsuites.Testsuite createTestsuitesTestsuite() {
        return new Testsuites.Testsuite();
    }

    /**
     * Create an instance of {@link com.tyson.hpqcjapi.types.Testsuite.Testcase.Error }
     * 
     */
    public com.tyson.hpqcjapi.types.Testsuite.Testcase.Error createTestsuiteTestcaseError() {
        return new com.tyson.hpqcjapi.types.Testsuite.Testcase.Error();
    }

    /**
     * Create an instance of {@link com.tyson.hpqcjapi.types.Testsuite.Testcase.Failure }
     * 
     */
    public com.tyson.hpqcjapi.types.Testsuite.Testcase.Failure createTestsuiteTestcaseFailure() {
        return new com.tyson.hpqcjapi.types.Testsuite.Testcase.Failure();
    }

    /**
     * Create an instance of {@link com.tyson.hpqcjapi.types.Testsuite.Properties.Property }
     * 
     */
    public com.tyson.hpqcjapi.types.Testsuite.Properties.Property createTestsuitePropertiesProperty() {
        return new com.tyson.hpqcjapi.types.Testsuite.Properties.Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.tyson.hpqcjapi.types.Testsuite }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testsuite")
    public JAXBElement<com.tyson.hpqcjapi.types.Testsuite> createTestsuite(com.tyson.hpqcjapi.types.Testsuite value) {
        return new JAXBElement<com.tyson.hpqcjapi.types.Testsuite>(_Testsuite_QNAME, com.tyson.hpqcjapi.types.Testsuite.class, null, value);
    }

}
